language: ruby
os: osx
env: OSX=10.11
osx_image: xcode7.3
rvm: system

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - sudo chown -R $USER $(brew --repo)
  - git -C $(brew --repo) reset --hard origin/master
  - git -C $(brew --repo) clean -qxdff
  - export HOMEBREW_DEVELOPER="1"
  - brew update
  - sudo brew install hfsleuth
  - export PATH="$PATH:/Library/TeX/texbin"
  - mkdir -p $(brew --repo)/Library/Taps/kai5263499
  - ln -s $PWD $(brew --repo)/Library/Taps/kai5263499/homebrew-infosec
  - cd $(brew --repo)/Library/Taps/kai5263499/homebrew-infosec
  - export TRAVIS_BUILD_DIR="$(brew --repo)/Library/Taps/kai5263499/homebrew-infosec"

script:
  - brew test-bot --no-bottle

notifications:
  email:
    on_success: never
    on_failure: always